### ISSUE TITLE
Can it work on existing worktree?

### ISSUE THREAD

**Issue by kerryj89** [windsonR/git-worktree-manage#1]
```
project-worktree/
    some-worktree-branch <-- spawned by `git worktree add ../some-worktree-branch` in main-project
    main-project <-- main project
```

PHPStorm project is pointed to `project-worktree/main-project`.  PHPStorm has no special handling of worktrees and expects each worktree to be a separate IDE project.  I assume this extension allows me to switch worktrees inside one IDE project window.  However, I can't see the other worktrees even after clicking on "Refresh" button.  Is it looking in another directory outside of parent - maybe configurable?

![screenshot-2023-11-16-RBymgPz2](https://github.com/windsonR/git-worktree-manage/assets/1977804/94ed0264-306f-43b2-a0a5-9e94310a7af6)

Is it required to start from clone like instruction says or can I use existing worktree repo?  Thanks.  I wish PHPStorm allows to handle worktree branches more seamlessly without needing new project windows.

**Comment by windsonR** [comment]
Plugin use `git worktree list ` to get all available worktree.
Maybe you can confirm that your `worktree` branch in the command's output?

**Comment by kerryj89** [comment]
```
project-worktree/
    some-worktree-branch
    main-project <-- I am inside this directory to get output below
```

`git worktree list` inside `main-project` produces results (redacted identifiables):

```
<user>@<host> main-project % git worktree list  
/Users/<user>/dev/project-worktree/main-project  bdb61b3b3 [<branch name>]
/Users/<user>/dev/project-worktree/some-worktree-branch     6d20fb09b [<branch name>]
```

I tried restarting PHPStorm and refreshing, but list git_worktree_manager dropdowns remain empty.  Worktree branches exist one directory above.  Thanks!

**Comment by windsonR** [comment]
I can't reproduce this.
But i found another issue that can not use origin branch to create worktree. And it fixed.

**Comment by kerryj89** [comment]
Thank you, I'll try it again when 1.0.5 is available in app.  I'll close this for now as it may be an isolated issue with me.  Anyone can feel free to reopen if they also have the issue.
